paths:
  raw_data: ./data/bank_data.csv
  eda: ./images/eda/
  models: ./models/
  results: ./images/results/

files:
  raw_data: bank_data.csv

data_processing:
  category_lst:
    - Gender
    - Education_Level
    - Marital_Status
    - Income_Category
    - Card_Category
  feature_lst:
    - Customer_Age
    - Dependent_count
    - Months_on_book
    - Total_Relationship_Count
    - Months_Inactive_12_mon
    - Contacts_Count_12_mon
    - Credit_Limit
    - Total_Revolving_Bal
    - Avg_Open_To_Buy
    - Total_Amt_Chng_Q4_Q1
    - Total_Trans_Amt
    - Total_Trans_Ct
    - Total_Ct_Chng_Q4_Q1
    - Avg_Utilization_Ratio
    - Gender_Churn
    - Education_Level_Churn
    - Marital_Status_Churn
    - Income_Category_Churn
    - Card_Category_Churn
  plot_vars:
    - Churn
    - Customer_Age
    - Marital_Status
    - Total_Trans_Ct
    - heatmap_all

models:
  random_forest:
    params:
      random_state: 42
    num_cv: 5
    cv_param_grid:
      n_estimators:
        - 200
        - 500
      max_features:
        - auto
        - sqrt
      max_depth:
        - 4
        - 5
        - 100
      criterion:
        - gini
        - entropy

  logistic_regression:
    params:
      solver: lbfgs
      max_iter: 3000

