paths:
  raw_data: ./data/census.csv
  model: ./model

data:
  label: salary
  cat_features:
    - workclass
    - education
    - marital-status
    - occupation
    - relationship
    - race
    - sex
    - native-country

random_forest:
  n_jobs: -1
  random_state: 0
  n_estimators: 100

training:
  test_size: 0.2
  