paths:
  raw_data: ./data/census.csv
  model: ./model
  metrics: ./metrics


data:
  label: salary
  cat_features:
    - workclass
    - education
    - marital_status
    - occupation
    - relationship
    - race
    - sex
    - native_country

random_forest:
  n_jobs: -1
  random_state: 0
  n_estimators: 100

training:
  test_size: 0.2
  random_state: 42
  
api:
  host: 127.0.0.1
  port: 8000
  url: http://${api.host}:${api.port}/predict