name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.2.2
  - requests=2.24.0
  - mlflow=1.26.0
  - pip:
      - wandb==0.13.3
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
