# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch when
  # there are changes to the build-ml-pipeline subrepository.
  push:
    branches:
      - main
    paths:
      - machine-learning-devops-engineer/build-ml-pipeline/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run_unit_tests"
  run_ml_pipeline_unit_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install poetry
        working-directory: ./machine-learning-devops-engineer/build-ml-pipeline/
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest
